version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: solana_history
  fractal:
    build: .
    ports:
      - "8899:8899"
    depends_on:
      - clickhouse
    environment:
      CGO_ENABLED: 1
